FROM ubuntu 

MAINTAINER EB2-2027



RUN apt-get update
RUN apt-get -y --force-yes install iproute2
RUN apt-get -y --force-yes install quagga
RUN apt-get -y --force-yes install telnet
RUN apt-get -y --force-yes install openssh-server
RUN apt-get -y --force-yes install iptables
RUN apt-get -y --force-yes install iputils-ping
RUN apt-get -y --force-yes install traceroute
RUN apt-get -y --force-yes install tcpdump
RUN apt-get -y --force-yes install iperf
RUN apt-get -y --force-yes install vim
RUN apt-get -y --force-yes install python
RUN apt-get -y --force-yes install python-pip
RUN pip install --upgrade pip
RUN apt-get -y --force-yes install python-pexpect
RUN pip install paramiko
RUN apt-get -y --force-yes install nano


ADD daemons /etc/quagga/daemons
ADD collect_capture.py /root/collect_capture.py
ADD readme_collect_captures.txt /root/readme_collect_captures.txt

RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump
RUN ln -s /usr/bin/tcpdump /usr/sbin/tcpdump
RUN cp /usr/share/doc/quagga/examples/zebra.conf.sample /etc/quagga/zebra.conf
RUN cp /usr/share/doc/quagga/examples/ospfd.conf.sample /etc/quagga/ospfd.conf
RUN cp /usr/share/doc/quagga/examples/ripd.conf.sample /etc/quagga/ripd.conf
RUN cp /usr/share/doc/quagga/examples/bgpd.conf.sample /etc/quagga/bgpd.conf
RUN cp /usr/share/doc/quagga/examples/vtysh.conf.sample /etc/quagga/vtysh.conf

RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config



RUN chown quagga:quagga /etc/quagga/*.conf
RUN chown quagga.quaggavty /etc/quagga/*.conf
RUN chmod 640 /etc/quagga/*.conf
